version: 2
jobs:
  lint:
    docker:
      - image: golangci/golangci-lint:v1.21.0
    steps:
      - checkout
      - run:
          name: "Run golangci-lint"
          command: golangci-lint run --color always --enable-all --exclude-use-default -D godox -D gochecknoglobals -D gochecknoinits -D lll -D wsl -D funlen -D whitespace
  
  release:
    docker:
      - image: circleci/golang:1.16
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  build:
    jobs:
      - lint
      - release:
          # Only run this job on git tag pushes
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
